(ns clj-fabric8.apis.core
  (:require [clj-fabric8.core :refer [defresource]]))

(def Binding (defresource "bindings" :version "v1" :kind "Binding" :scope "Namespaced"))
(def ComponentStatus (defresource "componentstatuses" :version "v1" :kind "ComponentStatus" :scope "Clustered"))
(def ConfigMap (defresource "configmaps" :version "v1" :kind "ConfigMap" :scope "Namespaced"))
(def Endpoints (defresource "endpoints" :version "v1" :kind "Endpoints" :scope "Namespaced"))
(def Event (defresource "events" :version "v1" :kind "Event" :scope "Namespaced"))
(def LimitRange (defresource "limitranges" :version "v1" :kind "LimitRange" :scope "Namespaced"))
(def Namespace (defresource "namespaces" :version "v1" :kind "Namespace" :scope "Clustered"))
(def Node (defresource "nodes" :version "v1" :kind "Node" :scope "Clustered"))
(def PersistentVolumeClaim (defresource "persistentvolumeclaims" :version "v1" :kind "PersistentVolumeClaim" :scope "Namespaced"))
(def PersistentVolume (defresource "persistentvolumes" :version "v1" :kind "PersistentVolume" :scope "Clustered"))
(def Pod (defresource "pods" :version "v1" :kind "Pod" :scope "Namespaced"))
(def PodTemplate (defresource "podtemplates" :version "v1" :kind "PodTemplate" :scope "Namespaced"))
(def ReplicationController (defresource "replicationcontrollers" :version "v1" :kind "ReplicationController" :scope "Namespaced"))
(def ResourceQuota (defresource "resourcequotas" :version "v1" :kind "ResourceQuota" :scope "Namespaced"))
(def Secret (defresource "secrets" :version "v1" :kind "Secret" :scope "Namespaced"))
(def ServiceAccount (defresource "serviceaccounts" :version "v1" :kind "ServiceAccount" :scope "Namespaced"))
(def Service (defresource "services" :version "v1" :kind "Service" :scope "Namespaced"))
